package com.freya02.botcommands.internal.commands.application.context.message.mixins

import com.freya02.botcommands.internal.commands.application.mixins.ITopLevelApplicationCommandInfo

interface ITopLevelMessageCommandInfo : ITopLevelApplicationCommandInfo