# https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties

version.major=3
version.minor=0
version.revision=0
version.classifier=beta.6

org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx2G
kotlin.daemon.jvmargs=-Xmx2G
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
# Don't register symbol processors for all source sets
ksp.allow.all.target.configuration=false
