package io.github.freya022.botcommands.internal.commands.application.context.message.mixins

import io.github.freya022.botcommands.internal.commands.application.mixins.ITopLevelApplicationCommandInfo

interface ITopLevelMessageCommandInfo : ITopLevelApplicationCommandInfo