package io.github.freya022.botcommands.internal.commands.application.slash.mixins

import io.github.freya022.botcommands.internal.commands.application.mixins.ITopLevelApplicationCommandInfo

interface ITopLevelSlashCommandInfo : ITopLevelApplicationCommandInfo