package com.freya02.botcommands.internal.commands.application.context.user.mixins

import com.freya02.botcommands.internal.commands.application.mixins.ITopLevelApplicationCommandInfo

interface ITopLevelUserCommandInfo : ITopLevelApplicationCommandInfo