# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format
[versions]
bucket4j = "8.14.0"
bytebuddy = "1.17.5"
caffeine = "3.2.3"
classgraph = "4.8.184"
flyway = "12.1.0"
h2 = "2.3.232"
hikaricp = "6.2.1"
jackson = "2.22.0"
javaStringSimilarity = "2.0.0"
jda = "6.5.0"
jdaEmojis = "3.0.0"
jemoji = "1.7.5"
jetbrainsAnnotations = "26.0.2"
jsr305 = "3.0.2"
junit = "6.0.1"
konsist = "0.17.3"
kotlin = "2.4.20"
kotlinLogging = "7.0.3"
kotlinx-coroutines = "1.11.0"
kotlinx-serialization = "1.11.0"
logbackClassic = "1.5.16"
mockk = "1.14.4"
postgresql = "42.7.7"
slf4j-api = "2.0.16"
# @pin For compatibility with Spring Boot 3
spring = "6.2.14"
# @pin Our code is compatible with Spring Boot 4, don't upgrade dependencies to avoid unexpected breakages
springBoot = "3.5.8"
trove4j-core = "3.1.0"

[plugins]
dokka = "org.jetbrains.dokka:2.2.0"
jmh = "me.champeau.jmh:0.7.3"
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:1.1.0"
mavenPublish = "com.vanniktech.maven.publish:0.37.0"

[libraries]
bucket4j-jdk17-core = { module = "com.bucket4j:bucket4j_jdk17-core", version.ref = "bucket4j" }
bucket4j-jdk17-postgresql = { module = "com.bucket4j:bucket4j_jdk17-postgresql", version.ref = "bucket4j" }
bytebuddy = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }
bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
javaStringSimilarity = { module = "info.debatty:java-string-similarity", version.ref = "javaStringSimilarity" }
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jdaEmojis = { module = "dev.freya02:jda-emojis", version.ref = "jdaEmojis" }
jemoji = { module = "net.fellbaum:jemoji", version.ref = "jemoji" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
jspecify = "org.jspecify:jspecify:1.0.0"
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-debug = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-debug", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
logbackClassic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
mockk = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
springBoot = { module = "org.springframework.boot:spring-boot", version.ref = "springBoot" }
springBoot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "springBoot" }
springBoot-devtools = "org.springframework.boot:spring-boot-devtools:4.0.0"
springBoot-starter = "org.springframework.boot:spring-boot-starter:4.0.0"
springBoot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springBoot" }
spring-context = { module = "org.springframework:spring-context", version.ref = "spring" }
trove4j-core = { module = "net.sf.trove4j:core", version.ref = "trove4j-core" }

[bundles]
test = [
    "junit",
    "junit-params",
    "kotlin-test-junit5",
]
