package com.freya02.botcommands.api.core.db

import java.sql.PreparedStatement
import java.sql.ResultSet

sealed class AbstractKPreparedStatement(val preparedStatement: PreparedStatement) : PreparedStatement by preparedStatement {
    // region execute

    @Deprecated("Use suspending version", level = DeprecationLevel.HIDDEN)
    override fun execute(): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun execute(sql: String?): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean = throw UnsupportedOperationException()

    // endregion

    // region executeUpdate

    @Deprecated("Use suspending version", level = DeprecationLevel.HIDDEN)
    override fun executeUpdate(): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun executeUpdate(sql: String?): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int = throw UnsupportedOperationException()

    // endregion

    // region executeQuery

    @Deprecated("Use suspending version", level = DeprecationLevel.HIDDEN)
    override fun executeQuery(): ResultSet = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.HIDDEN)
    override fun executeQuery(sql: String?): ResultSet = throw UnsupportedOperationException()

    // endregion
}