package io.github.freya022.botcommands.api.pagination.paginator

import dev.freya02.jda.emojis.unicode.Emojis
import io.github.freya022.botcommands.api.components.utils.ButtonContent
import io.github.freya022.botcommands.api.core.BContext
import io.github.freya022.botcommands.api.pagination.AbstractPaginationBuilder
import io.github.freya022.botcommands.api.pagination.PageEditor
import io.github.freya022.botcommands.api.pagination.Paginators
import io.github.freya022.botcommands.internal.utils.lazyWritable
import net.dv8tion.jda.api.EmbedBuilder
import net.dv8tion.jda.api.components.button.ButtonStyle
import net.dv8tion.jda.api.utils.messages.MessageCreateBuilder

/**
 * Classic paginator, where each page is generated by a [PageEditor].
 *
 * @see Paginators.paginator
 */
class Paginator internal constructor(
    context: BContext,
    builder: PaginatorBuilder
) : AbstractPaginator<Paginator>(
    context,
    builder
) {
    private val editor: PageEditor<Paginator> = builder.pageEditor

    override var maxPages: Int = builder.maxPages

    init {
        require(maxPages > 0) { "Max pages must be > 0" }
    }

    override fun writeMessage(builder: MessageCreateBuilder) {
        super.writeMessage(builder)

        val embedBuilder = EmbedBuilder()
        editor.accept(this, builder, embedBuilder, page)
        builder.setEmbeds(embedBuilder.build())
    }

    object Defaults {
        /** @see AbstractPaginationBuilder.cleanAfterRefresh */
        @JvmStatic
        var cleanAfterRefresh: Boolean = true

        /** @see PaginatorBuilder.setFirstContent */
        @JvmStatic
        var firstPageButtonContent: ButtonContent by lazyWritable { ButtonContent.fromEmoji(ButtonStyle.PRIMARY, Emojis.REWIND) }

        /** @see PaginatorBuilder.setPreviousContent */
        @JvmStatic
        var previousPageButtonContent: ButtonContent by lazyWritable { ButtonContent.fromEmoji(ButtonStyle.PRIMARY, Emojis.ARROW_BACKWARD) }

        /** @see PaginatorBuilder.setNextContent */
        @JvmStatic
        var nextPageButtonContent: ButtonContent by lazyWritable { ButtonContent.fromEmoji(ButtonStyle.PRIMARY, Emojis.ARROW_FORWARD) }

        /** @see PaginatorBuilder.setLastContent */
        @JvmStatic
        var lastPageButtonContent: ButtonContent by lazyWritable { ButtonContent.fromEmoji(ButtonStyle.PRIMARY, Emojis.FAST_FORWARD) }

        /** @see PaginatorBuilder.setDeleteContent */
        @JvmStatic
        var deleteButtonContent: ButtonContent by lazyWritable { ButtonContent.fromEmoji(ButtonStyle.DANGER, Emojis.WASTEBASKET) }

        /** @see PaginatorBuilder.useDeleteButton */
        @JvmStatic
        var useDeleteButton: Boolean = false
    }
}
