package io.github.freya022.botcommands.api.pagination.paginator

import io.github.freya022.botcommands.api.core.BContext
import io.github.freya022.botcommands.api.pagination.PageEditor
import io.github.freya022.botcommands.api.pagination.Paginators
import net.dv8tion.jda.api.EmbedBuilder
import net.dv8tion.jda.api.utils.messages.MessageCreateBuilder

/**
 * Classic paginator, where each page is generated by a [PageEditor].
 *
 * @see Paginators.paginator
 */
class Paginator internal constructor(
    context: BContext,
    builder: PaginatorBuilder
) : AbstractPaginator<Paginator>(
    context,
    builder
) {
    private val editor: PageEditor<Paginator> = builder.pageEditor

    override var maxPages: Int = builder.maxPages

    override fun writeMessage(builder: MessageCreateBuilder) {
        super.writeMessage(builder)

        val embedBuilder = EmbedBuilder()
        editor.accept(this, builder, embedBuilder, page)
        builder.setEmbeds(embedBuilder.build())
    }
}
