@file:Suppress("DeprecatedCallableAddReplaceWith")

package io.github.freya022.botcommands.api.core.db

import java.sql.PreparedStatement
import java.sql.ResultSet

class BlockingKPreparedStatement(preparedStatement: PreparedStatement) : AbstractKPreparedStatement(preparedStatement) {
    fun execute(vararg params: Any?): Boolean {
        setParameters(params)
        return preparedStatement.execute()
    }

    fun executeUpdate(vararg params: Any?): Int {
        setParameters(params)
        return preparedStatement.executeUpdate()
    }

    fun executeQuery(vararg params: Any?): DBResult {
        setParameters(params)
        return DBResult(preparedStatement.executeQuery())
    }

    // region execute

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun execute(sql: String?): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun execute(sql: String?, columnNames: Array<out String>?): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun execute(sql: String?, autoGeneratedKeys: Int): Boolean = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun execute(sql: String?, columnIndexes: IntArray?): Boolean = throw UnsupportedOperationException()

    // endregion

    // region executeUpdate

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun executeUpdate(sql: String?): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun executeUpdate(sql: String?, columnIndexes: IntArray?): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun executeUpdate(sql: String?, autoGeneratedKeys: Int): Int = throw UnsupportedOperationException()

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun executeUpdate(sql: String?, columnNames: Array<out String>?): Int = throw UnsupportedOperationException()

    // endregion

    // region executeQuery

    @Deprecated("This is never usable as this is a prepared statement", level = DeprecationLevel.ERROR)
    override fun executeQuery(sql: String?): ResultSet = throw UnsupportedOperationException()

    // endregion
}