package com.freya02.botcommands.internal.commands.application.slash.mixins

import com.freya02.botcommands.internal.commands.application.mixins.ITopLevelApplicationCommandInfo

interface ITopLevelSlashCommandInfo : ITopLevelApplicationCommandInfo