name: Check javadocs
on:
  workflow_dispatch:
  push:
    paths: 
      - 'pom.xml'
      - '**.java'
jobs:
  check-javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build Javadocs with Maven
        run: mvn -P check-docs -B javadoc:javadoc --file pom.xml
