name: Deploy KDocs to Pages

on:
  push:
    branches: ["3.X"]
    paths:       
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/main/**.kt'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Set release version
        run: mvn -B BotCommandsBuild:set-ci-version
      - name: Generate KDocs
        run: mvn -B -P docs generate-sources dokka:dokka
      - name: Upload staging repository
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./target/dokka
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4