name: Check compile, tests & KDocs
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 3.X
  push:
    branches: 
      - 3.X

concurrency:
  group: "validate"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run tests
        run: ./gradlew test

      - name: Build KDocs
        # Run even if tests failed, but only on PRs
        if: ${{ !cancelled() && github.event_name == 'pull_request' }}
        run: ./gradlew dokkaGenerate

      - name: Publish snapshot
        # Workflow dispatch, push or pull request from the original repo
        if: ${{ success() && (github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.id == github.repository_id)) }}
        run: ./gradlew publishAllPublicationsToReposilite
        env:
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
          ORG_GRADLE_PROJECT_reposiliteUsername: ${{ secrets.REPOSILITE_USERNAME }}
          ORG_GRADLE_PROJECT_reposilitePassword: ${{ secrets.REPOSILITE_PASSWORD }}
          ORG_GRADLE_PROJECT_mavenGpgSecretKey: ${{ secrets.GPG_SECRET_KEY }}
          ORG_GRADLE_PROJECT_mavenGpgKeyId: ${{ secrets.GPG_KEY_ID }}

      - name: Upload JUnit XML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: junit-xml-test-report
          path: '**/build/test-results/test'

      - name: Upload HTML Test Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v5
        with:
          name: junit-html-test-report
          path: '**/build/reports/tests/test'

      - name: Annotate Failed Tests
        uses: mikepenz/action-junit-report@v6.0.0
        if: ${{ !cancelled() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          annotate_only: 'true'
